name: Build

permissions:
  contents: write
  actions: write

on:
  workflow_dispatch:
#    inputs:
#      make_release:
#        description: 'Do you want to create a release?'
#        required: true
#        type: boolean
#       default: true

jobs:
#  build-batch-1:
#    strategy:
#      fail-fast: false
#      matrix:
#        include:
#          - model: OP11
#            soc: kalama
#            branch: oneplus/sm8550
#            manifest: oneplus_11_v.xml
#            android_version: android13
#            kernel_version: "5.15"
#          - model: OP11r
#            soc: waipio
#            branch: oneplus/sm8475
#            manifest: oneplus_11r_v.xml
#            android_version: android13
#            kernel_version: "5.10"
#          - model: OP12r
#            soc: kalama
#           branch: oneplus/sm8550
#            manifest: oneplus_12r_v.xml
#            android_version: android13
#            kernel_version: "5.15"
#          - model: OP-OPEN
#            soc: kalama
#            branch: oneplus/sm8550
#            manifest: oneplus_open_v.xml
#            android_version: android13
#            kernel_version: "5.15"
#          - model: OP-ACE-2
#            soc: waipio
#            branch: oneplus/sm8475
#            manifest: oneplus_ace2_v.xml
#            android_version: android13
#            kernel_version: "5.10"
#          - model: OP10t
#            soc: waipio
#            branch: oneplus/sm8475
#            manifest: oneplus_10t_v.xml
#            android_version: android12
#            kernel_version: "5.10"
#          - model: OP10pro
#            soc: waipio
#            branch: oneplus/sm8450
#            manifest: oneplus_10_pro_v.xml
#            android_version: android12
#            kernel_version: "5.10"
#          - model: OP-ACE-2-PRO
#            soc: kalama
#            branch: oneplus/sm8550
#            manifest: oneplus_ace2pro_v.xml
#            android_version: android13
#            kernel_version: "5.15"
#    uses: ./.github/workflows/build.yml
#    secrets: inherit
#    with:
#      model: ${{ matrix.model }}
#      soc: ${{ matrix.soc }}
#      branch: ${{ matrix.branch }}
#      manifest: ${{ matrix.manifest }}
#      android_version: ${{ matrix.android_version }}
#      kernel_version: ${{ matrix.kernel_version }}

  build-batch-2:
    # needs: build-batch-1
    strategy:
      fail-fast: false
      matrix:
        include:
          - model: OP13
            soc: sun
            branch: oneplus/sm8750
            manifest: oneplus_13.xml
            android_version: android15
            kernel_version: "6.6"
#          - model: OPAce5Pro
#            soc: sun
#            branch: oneplus/sm8750
#            manifest: oneplus_ace5_pro.xml
#            android_version: android15
#            kernel_version: "6.6"
#          - model: OP12
#            soc: pineapple
#            branch: oneplus/sm8650
#            manifest: oneplus12_v.xml
#            android_version: android14
#            kernel_version: "6.1"
          - model: OP13r
            soc: pineapple
            branch: oneplus/sm8650
            manifest: oneplus_13r.xml
            android_version: android14
            kernel_version: "6.1"
#          - model: OP-ACE-5
#            soc: pineapple
#            branch: oneplus/sm8650
#            manifest: oneplus_ace5.xml
#            android_version: android14
#            kernel_version: "6.1"
#          - model: OPNORD4
#            soc: pineapple
#           branch: oneplus/sm7675
#            manifest: oneplus_nord_4_v.xml
#            android_version: android14
#            kernel_version: "6.1"
#          - model: OPNORDCE4
#            soc: crow
#            branch: oneplus/sm7550
#            manifest: oneplus_nord_ce4_v.xml
#            android_version: android14
#            kernel_version: "5.15"
#          - model: OP-PAD-2
#            soc: pineapple
#            branch: oneplus/sm8650
#            manifest: oneplus_pad2_v.xml
#            android_version: android14
#            kernel_version: "6.1"
    uses: ./.github/workflows/build.yml
    secrets: inherit
    with:
      model: ${{ matrix.model }}
      soc: ${{ matrix.soc }}
      branch: ${{ matrix.branch }}
      manifest: ${{ matrix.manifest }}
      android_version: ${{ matrix.android_version }}
      kernel_version: ${{ matrix.kernel_version }} 
